(()=>{
const V='1.4.0';
const REPO_MANIFEST='https://raw.githubusercontent.com/Meldixx/PresenceWatch/main/install/manifest.json';
const S=vendetta.plugin.storage;
const R=vendetta.metro.common.React;
const N=vendetta.metro.common.ReactNative;
const F=vendetta.metro.common.FluxDispatcher;
const C=vendetta.metro.common.clipboard;
const P=new Map(), PL=new Map(), UN=[], PATCHED=new Set(), REPEAT=new Map();
let patchTimer=null, channelInnerUnpatch=null, maintenanceTimer=null, summaryTimer=null, started=Date.now();

const DEF={
  online:'🟢 {name} появился в сети • {platform}',
  offline:'⚫ {name} вышел из сети • был онлайн {duration}',
  status:'🟡 {name}: {status} • {platform}'
};
const CHANGELOG=[
  'Активности: игры, Spotify, стримы и Custom Status',
  'Отдельная страница каждого пользователя и расширенный Timeline',
  'Избранное, группы, собственный цвет и иконка',
  'Пресеты уведомлений и повторное уведомление',
  'Ежедневная сводка и автоматическая очистка истории',
  'Журнал ошибок, проверка обновлений, Changelog и глобальная пауза'
];
const COLORS=['#5865F2','#3BA55C','#F0B232','#ED4245','#EB459E','#9B59B6','#00A8FC','#747F8D'];
const ICONS=['👁','⭐','💙','🔥','🎮','🌙','🔔','👤'];
const PRESETS=[
  {id:'online',name:'Только вход',prefs:{online:true,offline:false,status:false,muted:false}},
  {id:'all',name:'Все изменения',prefs:{online:true,offline:true,status:true,muted:false}},
  {id:'inout',name:'Вход + выход',prefs:{online:true,offline:true,status:false,muted:false}},
  {id:'quiet',name:'Тихий',prefs:{online:false,offline:false,status:false,muted:true}}
];

S.users??={}; S.history??=[]; S.timeline??=[]; S.stats??={}; S.activities??={}; S.errors??=[];
S.templates={...DEF,...(S.templates||{})}; S.lastEventAt??=0; S.debug??={};
S.defaults??={online:true,offline:false,status:false}; S.cooldownSec=Number.isFinite(+S.cooldownSec)?Math.max(0,+S.cooldownSec):30;
S.quiet??={enabled:false,start:0,end:8}; S.sortMode??='online'; S.lastNotify??={}; S.groups??=[];
S.retentionDays=[7,30,90].includes(+S.retentionDays)?+S.retentionDays:30;
S.paused=!!S.paused; S.dailySummary??={enabled:false,hour:21,lastDate:''}; S.update??={current:V,latest:V,available:false,checkedAt:0};
S.seenVersion??=''; S.defaultRepeatMin=Number.isFinite(+S.defaultRepeatMin)?Math.max(0,+S.defaultRepeatMin):0;

const valid=id=>/^\d{15,22}$/.test(String(id||''));
const tracked=()=>Object.keys(S.users||{}).filter(valid);
const has=id=>!!S.users?.[String(id)];
const ps=x=>{x=String(x??'offline').toLowerCase();return ['online','idle','dnd'].includes(x)?x:'offline'};
const sl=x=>x==='online'?'В сети':x==='idle'?'Неактивен':x==='dnd'?'Не беспокоить':'Не в сети';
const dot=x=>x==='online'?'🟢':x==='idle'?'🌙':x==='dnd'?'⛔':'⚫';
const dur=ms=>{let s=Math.max(0,Math.floor((+ms||0)/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d}д ${h}ч`:h?`${h}ч ${m}м`:m?`${m}м ${s%60}с`:`${s%60}с`};
const ago=t=>{if(!t)return'Нет данных';let d=Date.now()-t;return d<30000?'Только что':d<3600000?`${Math.max(1,Math.floor(d/60000))} мин назад`:d<86400000?`${Math.floor(d/3600000)} ч назад`:new Date(t).toLocaleString()};
const dayKey=t=>{let d=t instanceof Date?t:new Date(t||Date.now());return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pstore=()=>{try{return vendetta.metro.findByStoreName('PresenceStore')}catch{return null}};
const ustore=()=>{try{return vendetta.metro.findByStoreName('UserStore')}catch{return null}};
const user=id=>{try{return ustore()?.getUser?.(String(id))}catch{return null}};
const uname=id=>{let u=user(id);return u?.globalName||u?.username||String(id)};
const alias=id=>S.users?.[String(id)]?.alias||'';
const displayName=id=>alias(id)||uname(id);
const status=id=>{try{let s=pstore();return ps(s?.getStatus?.(String(id))??s?.getPresence?.(String(id))?.status)}catch{return'offline'}};
const plat=o=>{if(!o||typeof o!=='object')return'Неизвестно';let a=Object.entries(o).filter(([,v])=>ps(v)!=='offline').map(([k])=>k==='mobile'?'Mobile':k==='desktop'?'Desktop':k==='web'?'Web':k);return a.join(' + ')||'Неизвестно'};
function platform(id,p){let c=p?.clientStatus??p?.client_status??p?.presence?.clientStatus??p?.presence?.client_status,r=plat(c);if(r!=='Неизвестно')return r;try{let s=pstore(),q=plat(s?.getClientStatus?.(String(id))??s?.getPresence?.(String(id))?.clientStatus);return q!=='Неизвестно'?q:(PL.get(String(id))||'Неизвестно')}catch{return PL.get(String(id))||'Неизвестно'}}
function avatar(id){let u=user(id);try{let x=u?.getAvatarURL?.(null,128,true)||u?.getAvatarURL?.();if(x)return x}catch{}return u?.avatar?`https://cdn.discordapp.com/avatars/${id}/${u.avatar}.png?size=128`:null}
const toast=x=>{try{vendetta.ui.toasts.showToast(String(x))}catch{}};
function logError(where,e){try{let x={at:Date.now(),where:String(where),message:String(e?.message||e),stack:String(e?.stack||'').slice(0,1200)};S.errors=[x,...(S.errors||[])].slice(0,100)}catch{}}
function notify(x){try{let n=N?.NativeModules?.PushNotificationAndroid;if(n?.presentLocalNotification){n.presentLocalNotification({alertTitle:'PresenceWatch',alertBody:x,message:x});return}}catch(e){logError('notify/native',e)}toast('PresenceWatch: '+x)}
function tpl(t,d){let v={name:d.name||d.id,id:d.id,status:sl(d.status),platform:d.platform||'Неизвестно',time:new Date(d.time||Date.now()).toLocaleTimeString(),duration:dur(d.duration)};return String(t||'').replace(/\{(name|id|status|platform|time|duration)\}/g,(_,k)=>v[k])}
function stat(id){id=String(id);let all={...S.stats},x=all[id]||{totalMs:0,lastSessionMs:0,sessionStarted:0,lastSeen:0,lastStatusAt:0,eventCount:0};if(!all[id]){all[id]=x;S.stats=all}return x}
function setStat(id,x){S.stats={...S.stats,[String(id)]:x}}
function prefs(id){let x=S.users?.[String(id)]?.prefs||{};return {online:x.online??!!S.defaults.online,offline:x.offline??!!S.defaults.offline,status:x.status??!!S.defaults.status,muted:!!x.muted}}
function patchUser(id,patch){id=String(id);if(!S.users[id])return;S.users={...S.users,[id]:{...S.users[id],...patch}}}
function setPrefs(id,patch){patchUser(id,{prefs:{...prefs(id),...patch}})}
function add(id,a=''){id=String(id||'').trim();if(!valid(id)){toast('Некорректный Discord ID');return false}S.users={...S.users,[id]:{favorite:false,group:'',color:COLORS[0],icon:ICONS[0],repeatMin:S.defaultRepeatMin,...(S.users[id]||{addedAt:Date.now()}),alias:a||S.users[id]?.alias||'',prefs:S.users[id]?.prefs||{...S.defaults,muted:false}}};P.set(id,status(id));PL.set(id,platform(id));stat(id);toast(`${displayName(id)} добавлен в PresenceWatch`);return true}
function clearRepeat(id){let t=REPEAT.get(String(id));if(t)clearTimeout(t);REPEAT.delete(String(id))}
function remove(id){id=String(id);clearRepeat(id);let u={...S.users};delete u[id];S.users=u;P.delete(id);PL.delete(id);toast(`${uname(id)} удалён из PresenceWatch`)}
function toggle(id){has(id)?remove(id):add(id)}
function prime(){for(const id of tracked()){let s=status(id);P.set(id,s);PL.set(id,platform(id));let x=stat(id);if(s!=='offline'&&!x.sessionStarted)setStat(id,{...x,sessionStarted:Date.now()});try{let a=pstore()?.getActivities?.(id)??pstore()?.getPresence?.(id)?.activities;if(Array.isArray(a))syncActivities(id,a,Date.now(),false)}catch(e){logError('prime/activity',e)}}}
function inQuietHours(){if(!S.quiet?.enabled)return false;let h=new Date().getHours(),a=Math.max(0,Math.min(23,+S.quiet.start||0)),b=Math.max(0,Math.min(23,+S.quiet.end||0));if(a===b)return false;return a<b?(h>=a&&h<b):(h>=a||h<b)}
function canNotify(id,type){let p=prefs(id);if(S.paused||p.muted||!p[type])return false;if(inQuietHours())return false;let key=`${id}:${type}`,last=+S.lastNotify?.[key]||0,cd=Math.max(0,+S.cooldownSec||0)*1000;if(cd&&Date.now()-last<cd)return false;S.lastNotify={...S.lastNotify,[key]:Date.now()};return true}
function activityType(x){let n=+x;return n===0?'Играет':n===1?'Стримит':n===2?'Слушает':n===3?'Смотрит':n===4?'Статус':n===5?'Соревнуется':'Активность'}
function normalizeActivities(arr){return (Array.isArray(arr)?arr:[]).filter(a=>a&&a.name).map(a=>({key:String(a.id||`${a.type}:${a.name}:${a.details||''}`),name:String(a.name),type:+a.type||0,label:activityType(a.type),details:String(a.details||''),state:String(a.state||''),startedAt:+a.timestamps?.start||0})).slice(0,12)}
function pushTimeline(e){S.timeline=[e,...(S.timeline||[])].slice(0,1500)}
function syncActivities(id,arr,now=Date.now(),record=true){id=String(id);let next=normalizeActivities(arr),prev=S.activities?.[id]?.items||[],pm=new Map(prev.map(x=>[x.key,x])),nm=new Map(next.map(x=>[x.key,x]));if(record){for(const a of next)if(!pm.has(a.key))pushTimeline({id,at:now,kind:'activity_start',activity:a});for(const a of prev)if(!nm.has(a.key))pushTimeline({id,at:now,kind:'activity_end',activity:a})}S.activities={...S.activities,[id]:{items:next,updatedAt:now}}}
function scheduleRepeat(id,c){clearRepeat(id);let min=Math.max(0,+S.users?.[id]?.repeatMin||0);if(!min)return;let t=setTimeout(()=>{REPEAT.delete(id);try{if(!has(id)||S.paused||status(id)==='offline')return;let p=prefs(id);if(p.muted||!p.online||inQuietHours())return;notify(`🔔 ${displayName(id)} всё ещё в сети • ${platform(id)}`)}catch(e){logError('repeat',e)}},min*60000);REPEAT.set(id,t)}
function event(p){try{let id=String(p?.user?.id??p?.userId??p?.user_id??p?.presence?.user?.id??p?.id??'');if(!has(id)||S.paused)return;let now=Date.now(),acts=p?.activities??p?.presence?.activities;if(Array.isArray(acts))syncActivities(id,acts,now,true);let n=ps(p?.status??p?.presence?.status??(Object.values(p?.clientStatus||p?.client_status||{})[0]))||status(id),o=P.has(id)?P.get(id):status(id),pl=platform(id,p);P.set(id,n);PL.set(id,pl);S.lastEventAt=now;if(o===n)return;let x=stat(id),sd=0;if(o==='offline'&&n!=='offline')x={...x,sessionStarted:now,lastStatusAt:now,eventCount:(x.eventCount||0)+1};else if(o!=='offline'&&n==='offline'){sd=Math.max(0,now-(x.sessionStarted||now));x={...x,totalMs:(x.totalMs||0)+sd,lastSessionMs:sd,sessionStarted:0,lastSeen:now,lastStatusAt:now,eventCount:(x.eventCount||0)+1};clearRepeat(id)}else x={...x,lastStatusAt:now,eventCount:(x.eventCount||0)+1};setStat(id,x);let nm=alias(id)||p?.user?.globalName||p?.user?.username||uname(id),entry={id,name:nm,at:now,from:o,to:n,platform:pl};S.history=[entry,...(S.history||[])].slice(0,1000);pushTimeline({...entry,kind:'status'});let c={id,name:nm,status:n,platform:pl,time:now,duration:sd};if(o==='offline'&&n!=='offline'){if(canNotify(id,'online'))notify(tpl(S.templates.online,c));scheduleRepeat(id,c)}else if(o!=='offline'&&n==='offline'){if(canNotify(id,'offline'))notify(tpl(S.templates.offline,c))}else if(o!=='offline'&&n!=='offline'){if(canNotify(id,'status'))notify(tpl(S.templates.status,c))}}catch(e){logError('presence event',e)}}

function cleanupData(){try{let cutoff=Date.now()-Math.max(1,+S.retentionDays||30)*86400000;S.history=(S.history||[]).filter(x=>+x.at>=cutoff).slice(0,1000);S.timeline=(S.timeline||[]).filter(x=>+x.at>=cutoff).slice(0,1500);S.errors=(S.errors||[]).slice(0,100)}catch(e){logError('cleanup',e)}}
function summaryText(){let start=new Date();start.setHours(0,0,0,0);let events=(S.history||[]).filter(e=>e.at>=+start),joins=events.filter(e=>e.from==='offline'&&e.to!=='offline'),online=tracked().filter(id=>status(id)!=='offline').length,counts={};for(const e of events)counts[e.id]=(counts[e.id]||0)+1;let top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([id,n])=>`${displayName(id)} — ${n}`).join(', ');return `📊 PresenceWatch за сегодня\nСобытий: ${events.length} • входов: ${joins.length} • сейчас онлайн: ${online}${top?`\nАктивнее всего: ${top}`:''}`}
function checkDailySummary(force=false){try{if(!force&&!S.dailySummary?.enabled)return;let now=new Date(),key=dayKey(now);if(!force&&(now.getHours()!==Math.max(0,Math.min(23,+S.dailySummary.hour||21))||S.dailySummary.lastDate===key))return;notify(summaryText());S.dailySummary={...S.dailySummary,lastDate:key}}catch(e){logError('daily summary',e)}}
async function checkUpdate(silent=false){try{let r=await fetch(`${REPO_MANIFEST}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);let m=await r.json(),latest=String(m?.hash||'').replace(/^presencewatch-/,'')||V;S.update={current:V,latest,hash:m?.hash||'',available:latest!==V,checkedAt:Date.now()};if(!silent)toast(latest===V?'Установлена актуальная версия':`Доступна версия ${latest}`);return S.update}catch(e){logError('update check',e);if(!silent)toast('Не удалось проверить обновления');return null}}

function getProfileItems(ret){try{let items=ret?.props?.items;if(Array.isArray(items)){if(Array.isArray(items[0]))return items[0];return items}items=ret?.props?.children?.props?.items;if(Array.isArray(items)){if(Array.isArray(items[0]))return items[0];return items}const node=vendetta.utils.findInReactTree(ret,n=>Array.isArray(n?.props?.items));items=node?.props?.items;if(Array.isArray(items)){if(Array.isArray(items[0]))return items[0];return items}}catch(e){logError('profile items',e)}return null}
function addProfileItem(items,id){if(!Array.isArray(items)||!valid(id))return false;if(items.some(x=>x?.id==='presencewatch-profile'||String(x?.label||'').includes('PresenceWatch')))return true;const item={id:'presencewatch-profile',label:'PresenceWatch',subLabel:has(id)?'Отслеживается':'Не отслеживается',action:()=>toggle(id)};const di=items.findIndex(x=>x?.variant==='destructive'||x?.isDestructive);di>=0?items.splice(di,0,item):items.push(item);return true}
function patchProfileNamed(name){if(PATCHED.has(name))return true;let mod=null;try{mod=vendetta.metro.findByName(name,false)}catch(e){logError(`find ${name}`,e)}if(!mod?.default)return false;try{const un=vendetta.patcher.after('default',mod,(args,ret)=>{try{const props=args?.[0]||{},id=String(props?.user?.id??props?.userId??'');if(!valid(id))return;if(addProfileItem(getProfileItems(ret),id))S.debug.profileInjected=true}catch(e){logError('profile patch runtime',e)}});UN.push(un);PATCHED.add(name);return true}catch(e){logError(`patch ${name}`,e);return false}}
function findActionGroups(tree){try{return vendetta.utils.findInReactTree(tree,n=>Array.isArray(n)&&String(n?.[0]?.type?.name||'')==='ActionSheetRowGroup')}catch(e){logError('findActionGroups',e);return null}}
function rowList(group){let c=group?.props?.children;return Array.isArray(c)?c:(c?[c]:[])}
function findEyeIcon(groups){try{for(const g of groups)for(const row of rowList(g)){const label=String(row?.props?.label??''),iconName=String(row?.props?.icon?.props?.IconComponent?.name??row?.props?.icon?.type?.name??'');if(/прочитан|read/i.test(label)||/eye/i.test(iconName))return row?.props?.icon}}catch(e){logError('findEyeIcon',e)}return null}
function patchChannelLongPress(){const name='ChannelLongPressActionSheet';if(PATCHED.has(name))return true;let mod=null;try{mod=vendetta.metro.findByName(name,false)}catch(e){logError('find channel sheet',e)}if(!mod?.default)return false;try{const outer=vendetta.patcher.after('default',mod,(_,ret)=>{try{const ch=ret?.props?.channel;if(!ch?.isDM?.())return;const id=String(ch?.getRecipientId?.()??'');if(!valid(id))return;try{channelInnerUnpatch?.()}catch{}channelInnerUnpatch=vendetta.patcher.after('type',ret,(_,component)=>{try{const groups=findActionGroups(component);if(!Array.isArray(groups)||!groups.length){S.debug.channelInjected=false;return}if(groups.some(g=>rowList(g).some(x=>x?.key==='presencewatch-channel-row'))){S.debug.channelInjected=true;return}const gi=groups.findIndex(g=>g?.type&&rowList(g).length);if(gi<0)return;const baseGroup=groups[gi],children=rowList(baseGroup),template=children[0];if(!template?.type)return;const eyeIcon=findEyeIcon(groups)??template?.props?.icon,row=R.cloneElement(template,{key:'presencewatch-channel-row',label:'PresenceWatch',subLabel:has(id)?'Отслеживается':'Не отслеживается',icon:eyeIcon,onPress:()=>{toggle(id);try{ret?.props?.onClose?.()}catch{}}}),next=[...children];next.splice(Math.min(1,next.length),0,row);groups[gi]=R.cloneElement(baseGroup,{children:next});S.debug.channelInjected=true}catch(e){S.debug.channelInjected=false;logError('channel inner patch',e)}})}catch(e){logError('channel outer runtime',e)}});UN.push(outer);PATCHED.add(name);return true}catch(e){logError('patch channel long press',e);return false}}
function tryInstallMenuPatches(){patchProfileNamed('UserProfileOverflowMenu');patchProfileNamed('BotUserProfileOverflowMenu');patchChannelLongPress();S.debug.patched=[...PATCHED]}
function startMenuPatches(){tryInstallMenuPatches();if(patchTimer)clearInterval(patchTimer);patchTimer=setInterval(tryInstallMenuPatches,1000)}

function exp(){try{C.setString(JSON.stringify({app:'PresenceWatch',version:V,users:S.users,stats:S.stats,history:S.history,timeline:S.timeline,activities:S.activities,templates:S.templates,defaults:S.defaults,cooldownSec:S.cooldownSec,quiet:S.quiet,sortMode:S.sortMode,groups:S.groups,retentionDays:S.retentionDays,dailySummary:S.dailySummary,paused:S.paused,defaultRepeatMin:S.defaultRepeatMin},null,2));toast('Настройки скопированы')}catch(e){logError('export',e);toast('Ошибка экспорта')}}
async function imp(){try{let d=JSON.parse(await Promise.resolve(C.getString()));if(d?.app!=='PresenceWatch'||typeof d.users!=='object')throw Error('неверный формат');let u={};for(const [id,x]of Object.entries(d.users))if(valid(id))u[id]={favorite:!!x?.favorite,group:String(x?.group||''),color:String(x?.color||COLORS[0]),icon:String(x?.icon||ICONS[0]),repeatMin:Math.max(0,+x?.repeatMin||0),alias:typeof x?.alias==='string'?x.alias:'',addedAt:+x?.addedAt||Date.now(),prefs:x?.prefs&&typeof x.prefs==='object'?x.prefs:undefined};S.users=u;S.stats=d.stats&&typeof d.stats==='object'?d.stats:S.stats;S.history=Array.isArray(d.history)?d.history.slice(0,1000):S.history;S.timeline=Array.isArray(d.timeline)?d.timeline.slice(0,1500):S.timeline;S.activities=d.activities&&typeof d.activities==='object'?d.activities:S.activities;S.templates={...DEF,...(d.templates||{})};S.defaults={online:true,offline:false,status:false,...(d.defaults||{})};S.cooldownSec=Math.max(0,+d.cooldownSec||0);S.quiet={enabled:false,start:0,end:8,...(d.quiet||{})};S.sortMode=['online','name','recent'].includes(d.sortMode)?d.sortMode:'online';S.groups=Array.isArray(d.groups)?d.groups.slice(0,30):[];S.retentionDays=[7,30,90].includes(+d.retentionDays)?+d.retentionDays:30;S.dailySummary={enabled:false,hour:21,lastDate:'',...(d.dailySummary||{})};S.paused=!!d.paused;S.defaultRepeatMin=Math.max(0,+d.defaultRepeatMin||0);prime();cleanupData();toast(`Импортировано: ${Object.keys(u).length}`)}catch(e){logError('import',e);toast('Ошибка импорта: '+(e?.message||e))}}

function Settings(){
  try{vendetta.storage.useProxy(S)}catch(e){logError('useProxy',e)}
  const h=R.createElement;
  const[,tick]=R.useState(0),[input,setInput]=R.useState(''),[search,setSearch]=R.useState(''),[selected,setSelected]=R.useState(null),[editId,setEditId]=R.useState(null),[editValue,setEditValue]=R.useState(''),[delId,setDelId]=R.useState(null),[cfgId,setCfgId]=R.useState(null),[groupInput,setGroupInput]=R.useState(''),[to,setTo]=R.useState(S.templates.online),[tf,setTf]=R.useState(S.templates.offline),[ts,setTs]=R.useState(S.templates.status),[cd,setCd]=R.useState(String(S.cooldownSec||0)),[qs,setQs]=R.useState(String(S.quiet?.start??0)),[qe,setQe]=R.useState(String(S.quiet?.end??8)),[summaryHour,setSummaryHour]=R.useState(String(S.dailySummary?.hour??21));
  R.useEffect(()=>{let t=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(t)},[]);
  const raw=tracked(),onlineCount=raw.filter(id=>status(id)!=='offline').length,now=Date.now(),h24=(S.history||[]).filter(e=>now-e.at<86400000),sessions24=h24.filter(e=>e.from==='offline'&&e.to!=='offline').length;
  const q=search.trim().toLowerCase();
  let ids=raw.filter(id=>!q||displayName(id).toLowerCase().includes(q)||uname(id).toLowerCase().includes(q)||id.includes(q));
  ids.sort((a,b)=>{let fa=!!S.users[a]?.favorite,fb=!!S.users[b]?.favorite;if(fa!==fb)return fb-fa;if(S.sortMode==='name')return displayName(a).localeCompare(displayName(b));if(S.sortMode==='recent')return (stat(b).lastStatusAt||0)-(stat(a).lastStatusAt||0);let sa=status(a)==='offline'?1:0,sb=status(b)==='offline'?1:0;return sa-sb||displayName(a).localeCompare(displayName(b))});
  const st={page:{padding:14,gap:12,paddingBottom:42},hero:{backgroundColor:'#17181b',borderRadius:20,padding:18,gap:12,borderWidth:1,borderColor:'#2a2c31'},card:{backgroundColor:'#1d1f23',borderRadius:18,padding:16,gap:11,borderWidth:1,borderColor:'#2a2c31'},user:{backgroundColor:'#1d1f23',borderRadius:18,padding:15,gap:11,borderWidth:1,borderColor:'#2a2c31'},row:{flexDirection:'row',alignItems:'center',gap:10},grow:{flex:1},title:{color:'#f7f8f9',fontSize:23,fontWeight:'800'},head:{color:'#f4f5f6',fontSize:17,fontWeight:'800'},text:{color:'#e5e7eb',fontSize:14},hint:{color:'#8f96a3',fontSize:12,lineHeight:17},muted:{color:'#777d87',fontSize:11},input:{backgroundColor:'#111214',color:'#fff',borderRadius:12,paddingHorizontal:13,paddingVertical:12,borderWidth:1,borderColor:'#303239'},inputMulti:{backgroundColor:'#111214',color:'#fff',borderRadius:12,paddingHorizontal:13,paddingVertical:12,borderWidth:1,borderColor:'#303239',minHeight:50,textAlignVertical:'top'},primary:{backgroundColor:'#5865F2',borderRadius:12,paddingVertical:12,paddingHorizontal:14,alignItems:'center'},secondary:{backgroundColor:'#2a2d33',borderRadius:11,paddingVertical:10,paddingHorizontal:12,alignItems:'center'},danger:{backgroundColor:'#4a292d',borderRadius:11,paddingVertical:10,paddingHorizontal:12,alignItems:'center'},danger2:{backgroundColor:'#b43742',borderRadius:11,paddingVertical:10,paddingHorizontal:12,alignItems:'center'},btn:{color:'#fff',fontWeight:'800',fontSize:13},avatar:{width:54,height:54,borderRadius:27,backgroundColor:'#303239'},bigAvatar:{width:74,height:74,borderRadius:37,backgroundColor:'#303239'},chips:{flexDirection:'row',gap:7,flexWrap:'wrap',marginTop:5},chip:{backgroundColor:'#2a2d33',borderRadius:999,paddingHorizontal:9,paddingVertical:5},chipText:{color:'#cfd2d8',fontSize:11,fontWeight:'700'},stats:{flexDirection:'row',gap:8},stat:{flex:1,backgroundColor:'#151619',borderRadius:12,padding:10,gap:3},statL:{color:'#767d89',fontSize:10,fontWeight:'700'},statV:{color:'#e8eaed',fontSize:12,fontWeight:'700'},buttons:{flexDirection:'row',gap:8},switch:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},metricRow:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:'#202228',borderRadius:14,padding:12,gap:3},metricNum:{color:'#fff',fontSize:20,fontWeight:'800'},metricLab:{color:'#8f96a3',fontSize:11},section:{color:'#8f96a3',fontSize:11,fontWeight:'800',textTransform:'uppercase',letterSpacing:.7},divider:{height:1,backgroundColor:'#2b2d31',marginVertical:2},pill:{backgroundColor:'#27292e',borderRadius:999,paddingHorizontal:10,paddingVertical:7},fav:{fontSize:20,color:'#fff'}};
  const saveAlias=id=>{let v=String(editValue||'').trim();patchUser(id,{alias:v});setEditId(null);setEditValue('');toast(v?'Имя сохранено':'Используется имя Discord')};
  const cycleSort=()=>{S.sortMode=S.sortMode==='online'?'name':S.sortMode==='name'?'recent':'online';tick(x=>x+1)};
  const saveGlobal=()=>{S.cooldownSec=Math.max(0,Math.min(3600,+cd||0));S.quiet={...S.quiet,start:Math.max(0,Math.min(23,+qs||0)),end:Math.max(0,Math.min(23,+qe||0))};S.dailySummary={...S.dailySummary,hour:Math.max(0,Math.min(23,+summaryHour||21))};toast('Настройки сохранены')};
  const addGroup=()=>{let name=groupInput.trim();if(!name)return;let id=`g${Date.now()}`;S.groups=[...(S.groups||[]),{id,name}].slice(0,30);setGroupInput('');toast('Группа добавлена')};
  const groupName=id=>(S.groups||[]).find(g=>g.id===id)?.name||'Без группы';
  const applyPreset=(id,p)=>{setPrefs(id,p.prefs);toast(`Пресет: ${p.name}`);tick(x=>x+1)};
  const cycleColor=id=>{let cur=S.users[id]?.color||COLORS[0],i=COLORS.indexOf(cur);patchUser(id,{color:COLORS[(i+1)%COLORS.length]});tick(x=>x+1)};
  const cycleIcon=id=>{let cur=S.users[id]?.icon||ICONS[0],i=ICONS.indexOf(cur);patchUser(id,{icon:ICONS[(i+1)%ICONS.length]});tick(x=>x+1)};
  const cycleGroup=id=>{let all=['',...(S.groups||[]).map(g=>g.id)],cur=S.users[id]?.group||'',i=all.indexOf(cur);patchUser(id,{group:all[(i+1)%all.length]});tick(x=>x+1)};
  const cycleRepeat=id=>{let vals=[0,5,10,30,60],cur=+S.users[id]?.repeatMin||0,i=vals.indexOf(cur);patchUser(id,{repeatMin:vals[(i+1)%vals.length]});tick(x=>x+1)};

  if(selected&&has(selected)){
    let id=selected,u=user(id),s=status(id),x=stat(id),pl=platform(id),a=avatar(id),pf=prefs(id),acts=S.activities?.[id]?.items||[],tl=(S.timeline||[]).filter(e=>e.id===id).slice(0,60),color=S.users[id]?.color||COLORS[0],icon=S.users[id]?.icon||ICONS[0],cur=s!=='offline'&&x.sessionStarted?Date.now()-x.sessionStarted:0,total=(x.totalMs||0)+cur;
    return h(N.ScrollView,{contentContainerStyle:st.page,keyboardShouldPersistTaps:'handled'},
      h(N.Pressable,{style:st.secondary,onPress:()=>setSelected(null)},h(N.Text,{style:st.btn},'← Назад к списку')),
      h(N.View,{style:[st.hero,{borderLeftWidth:4,borderLeftColor:color}]},h(N.View,{style:st.row},a?h(N.Image,{source:{uri:a},style:st.bigAvatar}):h(N.View,{style:st.bigAvatar}),h(N.View,{style:st.grow},h(N.Text,{style:st.title},`${icon} ${displayName(id)}`),h(N.Text,{style:st.hint},u?.username?`@${u.username} • ${id}`:id),h(N.Text,{style:st.text},`${dot(s)} ${sl(s)} • ${pl}`))),h(N.View,{style:st.metricRow},h(N.View,{style:st.metric},h(N.Text,{style:st.metricNum},dur(total)),h(N.Text,{style:st.metricLab},'Всего онлайн')),h(N.View,{style:st.metric},h(N.Text,{style:st.metricNum},String(x.eventCount||0)),h(N.Text,{style:st.metricLab},'Событий')),h(N.View,{style:st.metric},h(N.Text,{style:st.metricNum},groupName(S.users[id]?.group)),h(N.Text,{style:st.metricLab},'Группа')))),
      h(N.View,{style:st.card},h(N.Text,{style:st.section},'Оформление и организация'),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'⭐ Избранный'),h(N.Switch,{value:!!S.users[id]?.favorite,onValueChange:v=>patchUser(id,{favorite:v})})),h(N.View,{style:st.buttons},h(N.Pressable,{style:[st.secondary,{flex:1,borderWidth:1,borderColor:color}],onPress:()=>cycleColor(id)},h(N.Text,{style:st.btn},'Цвет')),h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:()=>cycleIcon(id)},h(N.Text,{style:st.btn},`Иконка ${icon}`)),h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:()=>cycleGroup(id)},h(N.Text,{style:st.btn},groupName(S.users[id]?.group))))),
      h(N.View,{style:st.card},h(N.Text,{style:st.section},'Активности'),...(acts.length?acts.map((a,i)=>h(N.View,{key:a.key||i,style:st.stat},h(N.Text,{style:st.statV},`${a.label}: ${a.name}`),a.details?h(N.Text,{style:st.hint},a.details):null,a.state?h(N.Text,{style:st.hint},a.state):null)):[h(N.Text,{key:'na',style:st.hint},'Сейчас видимых активностей нет.')])) ,
      h(N.View,{style:st.card},h(N.Text,{style:st.section},'Пресеты уведомлений'),h(N.View,{style:{gap:8}},...PRESETS.map(p=>h(N.Pressable,{key:p.id,style:st.secondary,onPress:()=>applyPreset(id,p)},h(N.Text,{style:st.btn},p.name)))),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'Появился в сети'),h(N.Switch,{value:pf.online,onValueChange:v=>setPrefs(id,{online:v})})),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'Вышел из сети'),h(N.Switch,{value:pf.offline,onValueChange:v=>setPrefs(id,{offline:v})})),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'Online / Idle / DND'),h(N.Switch,{value:pf.status,onValueChange:v=>setPrefs(id,{status:v})})),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'Без уведомлений'),h(N.Switch,{value:pf.muted,onValueChange:v=>setPrefs(id,{muted:v})})),h(N.Pressable,{style:st.secondary,onPress:()=>cycleRepeat(id)},h(N.Text,{style:st.btn},`Повторное уведомление: ${+S.users[id]?.repeatMin||0?`${S.users[id].repeatMin} мин`:'выкл.'}`))),
      h(N.View,{style:st.card},h(N.Text,{style:st.section},'Расширенный Timeline'),...(tl.length?tl.map((e,i)=>h(N.View,{key:`${e.at}-${i}`,style:{backgroundColor:'#151619',borderRadius:12,padding:11,gap:3}},h(N.View,{style:st.row},h(N.Text,{style:[st.text,st.grow,{fontWeight:'700'}]},e.kind==='status'?`${dot(e.to)} ${sl(e.from)} → ${sl(e.to)}`:e.kind==='activity_start'?`▶ ${e.activity?.label}: ${e.activity?.name}`:`■ Завершено: ${e.activity?.name}`),h(N.Text,{style:st.muted},new Date(e.at).toLocaleString())),e.platform?h(N.Text,{style:st.hint},e.platform):null)):[h(N.Text,{key:'emptytl',style:st.hint},'Timeline пока пуст.')]))
    );
  }

  const cards=ids.map(id=>{let u=user(id),s=status(id),x=stat(id),pl=platform(id),a=avatar(id),editing=editId===id,confirm=delId===id,open=cfgId===id,pf=prefs(id),events24=h24.filter(e=>e.id===id).length,color=S.users[id]?.color||COLORS[0],icon=S.users[id]?.icon||ICONS[0],fav=!!S.users[id]?.favorite;return h(N.View,{key:id,style:[st.user,{borderLeftWidth:4,borderLeftColor:color}]},
    h(N.View,{style:st.row},a?h(N.Image,{source:{uri:a},style:st.avatar}):h(N.View,{style:st.avatar}),h(N.View,{style:st.grow},h(N.Text,{style:st.head},`${fav?'⭐ ':''}${icon} ${displayName(id)}`),h(N.Text,{style:st.hint},u?.username?`@${u.username}`:`ID ${id}`),h(N.View,{style:st.chips},h(N.View,{style:st.chip},h(N.Text,{style:st.chipText},`${dot(s)} ${sl(s)}`)),h(N.View,{style:st.chip},h(N.Text,{style:st.chipText},`📱 ${pl}`)),S.users[id]?.group?h(N.View,{style:st.chip},h(N.Text,{style:st.chipText},groupName(S.users[id].group))):null,pf.muted?h(N.View,{style:st.chip},h(N.Text,{style:st.chipText},'🔕')):null))),
    h(N.View,{style:st.stats},h(N.View,{style:st.stat},h(N.Text,{style:st.statL},'ПОСЛЕДНИЙ РАЗ'),h(N.Text,{style:st.statV},s==='offline'?ago(x.lastSeen):'Сейчас')),h(N.View,{style:st.stat},h(N.Text,{style:st.statL},'ПОСЛ. СЕССИЯ'),h(N.Text,{style:st.statV},x.lastSessionMs?dur(x.lastSessionMs):'—')),h(N.View,{style:st.stat},h(N.Text,{style:st.statL},'СОБЫТИЙ 24Ч'),h(N.Text,{style:st.statV},String(events24)))),
    editing?h(N.View,{style:{gap:8}},h(N.TextInput,{style:st.input,value:editValue,onChangeText:setEditValue,placeholder:uname(id),placeholderTextColor:'#666b74',autoFocus:true}),h(N.View,{style:st.buttons},h(N.Pressable,{style:[st.primary,{flex:1}],onPress:()=>saveAlias(id)},h(N.Text,{style:st.btn},'Сохранить')),h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:()=>{setEditId(null);setEditValue('')}},h(N.Text,{style:st.btn},'Отмена')))):null,
    open?h(N.View,{style:{gap:10}},h(N.View,{style:st.divider}),h(N.Text,{style:st.section},'Быстрые настройки'),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'⭐ Избранный'),h(N.Switch,{value:fav,onValueChange:v=>patchUser(id,{favorite:v})})),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'Без уведомлений'),h(N.Switch,{value:pf.muted,onValueChange:v=>setPrefs(id,{muted:v})})),h(N.Text,{style:st.hint},`Активностей сейчас: ${(S.activities?.[id]?.items||[]).length} • Группа: ${groupName(S.users[id]?.group)}`)):null,
    h(N.View,{style:st.buttons},h(N.Pressable,{style:[st.primary,{flex:1}],onPress:()=>setSelected(id)},h(N.Text,{style:st.btn},'Открыть')),h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:()=>{setCfgId(open?null:id);setEditId(null)}},h(N.Text,{style:st.btn},'⚙')),h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:()=>{setDelId(null);setEditId(id);setEditValue(alias(id)||u?.globalName||u?.username||'')}},h(N.Text,{style:st.btn},'✏️')),h(N.Pressable,{style:[confirm?st.danger2:st.danger,{flex:1}],onPress:()=>{if(confirm){remove(id);setDelId(null);if(cfgId===id)setCfgId(null)}else{setDelId(id);setTimeout(()=>setDelId(x=>x===id?null:x),4000)}}},h(N.Text,{style:st.btn},confirm?'Точно?':'Удалить')))
  )});

  return h(N.ScrollView,{contentContainerStyle:st.page,keyboardShouldPersistTaps:'handled'},
    h(N.View,{style:st.hero},h(N.View,{style:st.row},h(N.View,{style:st.grow},h(N.Text,{style:st.title},'PresenceWatch'),h(N.Text,{style:st.hint},`VERSION ${V} • ${S.paused?'⏸ Пауза':'● Активен'}`)),h(N.Switch,{value:!S.paused,onValueChange:v=>{S.paused=!v;if(S.paused)for(const id of REPEAT.keys())clearRepeat(id);tick(x=>x+1)}})),h(N.View,{style:st.metricRow},h(N.View,{style:st.metric},h(N.Text,{style:st.metricNum},String(raw.length)),h(N.Text,{style:st.metricLab},'Отслеживается')),h(N.View,{style:st.metric},h(N.Text,{style:st.metricNum},String(onlineCount)),h(N.Text,{style:st.metricLab},'Онлайн')),h(N.View,{style:st.metric},h(N.Text,{style:st.metricNum},String(h24.length)),h(N.Text,{style:st.metricLab},'Событий 24ч'))),h(N.Text,{style:st.hint},`Запущен: ${ago(started)} • Последнее событие: ${S.lastEventAt?ago(S.lastEventAt):'ещё не было'}`),h(N.Text,{style:st.hint},`Меню профиля: ${S.debug.profileInjected?'OK':'ожидание'} • Long press: ${S.debug.channelInjected?'OK':'ожидание'}`)),
    S.seenVersion!==V?h(N.View,{style:st.card},h(N.Text,{style:st.section},'Что нового'),h(N.Text,{style:st.head},`PresenceWatch ${V}`),...CHANGELOG.map((x,i)=>h(N.Text,{key:i,style:st.text},`• ${x}`)),h(N.Pressable,{style:st.secondary,onPress:()=>{S.seenVersion=V;tick(x=>x+1)}},h(N.Text,{style:st.btn},'Понятно'))):null,
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Watchlist'),h(N.TextInput,{style:st.input,value:input,onChangeText:setInput,keyboardType:'numeric',placeholder:'Discord ID',placeholderTextColor:'#666b74'}),h(N.Pressable,{style:st.primary,onPress:()=>{if(add(input))setInput('')}},h(N.Text,{style:st.btn},'＋ Добавить')),h(N.TextInput,{style:st.input,value:search,onChangeText:setSearch,placeholder:'Поиск по имени, username или ID',placeholderTextColor:'#666b74'}),h(N.Pressable,{style:st.secondary,onPress:cycleSort},h(N.Text,{style:st.btn},`Сортировка: ${S.sortMode==='online'?'онлайн сначала':S.sortMode==='name'?'по имени':'по активности'}`))),
    ...cards,
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Группы'),h(N.View,{style:st.buttons},h(N.TextInput,{style:[st.input,{flex:1}],value:groupInput,onChangeText:setGroupInput,placeholder:'Название группы',placeholderTextColor:'#666b74'}),h(N.Pressable,{style:st.primary,onPress:addGroup},h(N.Text,{style:st.btn},'Добавить'))),...(S.groups||[]).map(g=>h(N.View,{key:g.id,style:st.row},h(N.Text,{style:[st.text,st.grow]},g.name),h(N.Pressable,{style:st.danger,onPress:()=>{S.groups=S.groups.filter(x=>x.id!==g.id);for(const id of tracked())if(S.users[id]?.group===g.id)patchUser(id,{group:''});tick(x=>x+1)}},h(N.Text,{style:st.btn},'Удалить'))))),
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Сводка и хранение'),h(N.View,{style:st.switch},h(N.View,{style:st.grow},h(N.Text,{style:st.text},'Ежедневная сводка'),h(N.Text,{style:st.hint},'Системное уведомление один раз в день')),h(N.Switch,{value:!!S.dailySummary?.enabled,onValueChange:v=>S.dailySummary={...S.dailySummary,enabled:v}})),h(N.TextInput,{style:st.input,value:summaryHour,onChangeText:setSummaryHour,keyboardType:'numeric',placeholder:'Час, например 21',placeholderTextColor:'#666b74'}),h(N.Pressable,{style:st.secondary,onPress:()=>checkDailySummary(true)},h(N.Text,{style:st.btn},'Показать сводку сейчас')),h(N.Pressable,{style:st.secondary,onPress:()=>{S.retentionDays=S.retentionDays===7?30:S.retentionDays===30?90:7;cleanupData();tick(x=>x+1)}},h(N.Text,{style:st.btn},`Хранить историю: ${S.retentionDays} дней`))),
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Уведомления'),h(N.Text,{style:st.hint},'Cooldown в секундах'),h(N.TextInput,{style:st.input,value:cd,onChangeText:setCd,keyboardType:'numeric',placeholder:'30',placeholderTextColor:'#666b74'}),h(N.View,{style:st.switch},h(N.Text,{style:st.text},'Тихие часы'),h(N.Switch,{value:!!S.quiet?.enabled,onValueChange:v=>S.quiet={...S.quiet,enabled:v}})),h(N.View,{style:st.buttons},h(N.TextInput,{style:[st.input,{flex:1}],value:qs,onChangeText:setQs,keyboardType:'numeric',placeholder:'С 0',placeholderTextColor:'#666b74'}),h(N.TextInput,{style:[st.input,{flex:1}],value:qe,onChangeText:setQe,keyboardType:'numeric',placeholder:'До 8',placeholderTextColor:'#666b74'})),h(N.Pressable,{style:st.primary,onPress:saveGlobal},h(N.Text,{style:st.btn},'Сохранить настройки')),h(N.Pressable,{style:st.secondary,onPress:()=>notify('🟢 Тестовое уведомление PresenceWatch')},h(N.Text,{style:st.btn},'🔔 Проверить уведомление'))),
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Тексты уведомлений'),h(N.Text,{style:st.hint},'Переменные: {name} {id} {status} {platform} {time} {duration}'),h(N.TextInput,{style:st.inputMulti,value:to,onChangeText:setTo,multiline:true}),h(N.TextInput,{style:st.inputMulti,value:tf,onChangeText:setTf,multiline:true}),h(N.TextInput,{style:st.inputMulti,value:ts,onChangeText:setTs,multiline:true}),h(N.Pressable,{style:st.primary,onPress:()=>{S.templates={online:to||DEF.online,offline:tf||DEF.offline,status:ts||DEF.status};toast('Тексты сохранены')}},h(N.Text,{style:st.btn},'Сохранить шаблоны'))),
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Обновления'),h(N.Text,{style:st.text},`Установлена: ${V}`),h(N.Text,{style:st.hint},`Последняя: ${S.update?.latest||'не проверялась'}${S.update?.available?' • доступно обновление':''}`),h(N.Pressable,{style:st.secondary,onPress:()=>checkUpdate(false)},h(N.Text,{style:st.btn},'Проверить обновления'))),
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Журнал ошибок'),...(S.errors?.length?S.errors.slice(0,12).map((e,i)=>h(N.View,{key:`err-${e.at}-${i}`,style:st.stat},h(N.Text,{style:st.statV},`${e.where}: ${e.message}`),h(N.Text,{style:st.hint},new Date(e.at).toLocaleString()))):[h(N.Text,{key:'noerr',style:st.hint},'Ошибок пока нет.')]),h(N.View,{style:st.buttons},h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:()=>{try{C.setString(JSON.stringify(S.errors||[],null,2));toast('Лог скопирован')}catch(e){logError('copy errors',e)}}},h(N.Text,{style:st.btn},'Скопировать лог')),h(N.Pressable,{style:[st.danger,{flex:1}],onPress:()=>{S.errors=[];tick(x=>x+1)}},h(N.Text,{style:st.btn},'Очистить')))),
    h(N.View,{style:st.card},h(N.Text,{style:st.section},'Экспорт / импорт'),h(N.View,{style:st.buttons},h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:exp},h(N.Text,{style:st.btn},'Экспорт')),h(N.Pressable,{style:[st.secondary,{flex:1}],onPress:imp},h(N.Text,{style:st.btn},'Импорт')))),
    h(N.Text,{style:st.hint},'Invisible отображается как Offline. Активности видны только если Discord-клиент действительно получает их через presence.')
  );
}

return{
  onLoad(){try{started=Date.now();cleanupData();prime();F.subscribe('PRESENCE_UPDATE',event);startMenuPatches();maintenanceTimer=setInterval(cleanupData,3600000);summaryTimer=setInterval(()=>checkDailySummary(false),60000);checkUpdate(true)}catch(e){logError('onLoad',e)}},
  onUnload(){try{F.unsubscribe('PRESENCE_UPDATE',event)}catch{};if(patchTimer)clearInterval(patchTimer);if(maintenanceTimer)clearInterval(maintenanceTimer);if(summaryTimer)clearInterval(summaryTimer);try{channelInnerUnpatch?.()}catch{};for(const id of REPEAT.keys())clearRepeat(id);for(const u of UN.splice(0))try{u?.()}catch{};PATCHED.clear();P.clear();PL.clear()},
  settings:Settings
}
})()